//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDolgah
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        private DbEntities()
            : base("name=DbEntities")
        {
        }
        static DbEntities ins;
        public static DbEntities Instance
        {
            get
            {
                if (ins == null)
                    ins = new DbEntities();
                return ins;
            }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<debt> debts { get; set; }
        public DbSet<debt_log> debt_log { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<user> users { get; set; }
    }
}
