//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDolgah
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend
    {
        public int id { get; set; }
        public int first { get; set; }
        public int second { get; set; }
        public Nullable<bool> validated { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
