//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDolgah
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public group()
        {
            this.debt_log = new HashSet<debt_log>();
            this.users = new HashSet<user>();
        }
    
        public int idgroups { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<debt_log> debt_log { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
