//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDolgah
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.debts = new HashSet<debt>();
            this.debts1 = new HashSet<debt>();
            this.friends = new HashSet<friend>();
            this.friends1 = new HashSet<friend>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string password_hesh { get; set; }
        public string salt { get; set; }
        public string avatar { get; set; }
    
        public virtual ICollection<debt> debts { get; set; }
        public virtual ICollection<debt> debts1 { get; set; }
        public virtual ICollection<friend> friends { get; set; }
        public virtual ICollection<friend> friends1 { get; set; }
    }
}
