//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDolgah
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        static DBEntities instance = null;
        private DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static DBEntities Instance
        {
            get 
            {
                if (instance == null) 
                    instance = new DBEntities();
                return instance;
            }
        }
    
        public DbSet<debt> debts { get; set; }
        public DbSet<friend> friends { get; set; }
        public DbSet<user> users { get; set; }
    }
}
